[phases.build]
cmds = ["mvn clean package -DskipTests -q -T 1C"]

[phases.start]
cmd = "java -Xmx512m -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/library-management-system-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx768m -XX:+UseG1GC"